# Generated by Django 4.0.7 on 2022-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_client_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_op',
            field=models.IntegerField(),
        ),
    ]
