# Generated by Django 4.0.7 on 2022-09-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('clients', '0006_rename_client_op_client_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag'),
        ),
    ]
