global:
  scrape_interval: 10s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 10s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: notify_api   # your project name
    metrics_path: /metrics
    static_configs:
      - targets:
        - django:8000