# Generated by Django 4.1.1 on 2022-09-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrib',
            name='message_client_id',
        ),
        migrations.RemoveField(
            model_name='distrib',
            name='message_distrib_id',
        ),
    ]
