# Generated by Django 4.0.7 on 2022-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0002_remove_distrib_message_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrib',
            name='distrib_id',
            field=models.IntegerField(),
        ),
    ]
