# Generated by Django 4.0.7 on 2022-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0003_alter_distrib_distrib_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrib',
            name='distrib_id',
        ),
        migrations.AlterField(
            model_name='distrib',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
