# Generated by Django 4.0.7 on 2022-09-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0004_remove_distrib_distrib_id_alter_distrib_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrib',
            old_name='distrib_begin_time',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='distrib',
            old_name='distrib_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='distrib',
            old_name='distrib_op',
            new_name='operator',
        ),
        migrations.RenameField(
            model_name='distrib',
            old_name='distrib_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='distrib',
            old_name='ditrib_text',
            new_name='text',
        ),
    ]
