# Generated by Django 4.0.7 on 2022-09-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_client_op_client_operator_and_more'),
        ('distribs', '0005_rename_distrib_begin_time_distrib_begin_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrib',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='distrib',
            name='tag',
        ),
        migrations.AddField(
            model_name='distrib',
            name='cl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
    ]
