# Generated by Django 4.0.7 on 2022-09-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_client_op_client_operator_and_more'),
        ('distribs', '0006_remove_distrib_operator_remove_distrib_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrib',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
    ]
