# Generated by Django 4.0.7 on 2022-09-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0007_alter_distrib_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrib',
            name='cl',
        ),
    ]
