# Generated by Django 4.0.7 on 2022-09-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('distribs', '0009_distrib_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrib',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag'),
            preserve_default=False,
        ),
    ]
