# Generated by Django 4.1.1 on 2022-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_status', models.CharField(max_length=255)),
                ('message_distrib_id', models.CharField(max_length=255)),
                ('message_client_id', models.CharField(max_length=255)),
            ],
        ),
    ]
