# Generated by Django 4.0.7 on 2022-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_distrib_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(),
        ),
    ]
