# Generated by Django 4.0.7 on 2022-09-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0003_remove_message_message_id_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_time',
            new_name='time',
        ),
    ]
