# Generated by Django 4.0.7 on 2022-09-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribs', '0006_remove_distrib_operator_remove_distrib_tag_and_more'),
        ('mymessages', '0005_remove_message_message_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='distrib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='distribs.distrib'),
        ),
    ]
